version: '3.8'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-docker-app-ecommerce-backend
    ports:
      - ${PORT}:3000
    depends_on:
      - db
    volumes:
      - ./src:/app/src

  db:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./prod_db:/var/lib/mysql'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - 3004:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}

volumes:
  db_data:
